inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "db/schema.rb"
    - "db/migrate/*"
    - "vendor/**/*"
    - "tmp/**/*"
    - "log/**/*"
    - "node_modules/**/*"
    - "sorbet/**/*"

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/**/*"

# syntax_treeとの整合性を保つために以下のCopは無効化しています。
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/CommentIndentation:
  Enabled: false
Layout/FirstHashElementIndentation:
  Enabled: false
Layout/MultilineHashBraceLayout:
  Enabled: false
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Style/HashSyntax:
  EnforcedShorthandSyntax: either
