# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::CI; end
module ActionMailer::Base::Mail::Message; end
module ActionMailer::Collector; end
module Bundler::FetchMetadata; end
module Bundler::MatchMetadata; end
